name: ParticlemanStyles
version: 1.0-SNAPSHOT
description: Bedrock particle loader for Player Particles plugin allowing styles to be authored in JSON or via Snowstorm GUI
# We could place every author in the authors list, but chose not to for illustrative purposes
# Also, having an author distinguishes that person as the project lead, and ensures their
# name is displayed first
author: Eliot Lash
authors: [Eliot Lash]
#website:

main: com.eliotlash.particlemanstyles.ParticlemanStyles
api-version: 1.16
database: false
depend: [PlayerParticles]

#  commands:
#    flagrate:
#      description: Set yourself on fire.
#      aliases: [combust_me, combustMe]
#      permission: inferno.flagrate
#      usage: Syntax error! Simply type /&lt;command&gt; to ignite yourself.
#    burningdeaths:
#      description: List how many times you have died by fire.
#      aliases: [burning_deaths, burningDeaths]
#      permission: inferno.burningdeaths
#      usage: |
#        /&lt;command&gt; [player]
#        Example: /&lt;command&gt; - see how many times you have burned to death
#        Example: /&lt;command&gt; CaptainIce - see how many times CaptainIce has burned to death

#  permissions:
#    inferno.*:
#      description: Gives access to all Inferno commands
#      children:
#        inferno.flagrate: true
#        inferno.burningdeaths: true
#        inferno.burningdeaths.others: true
#    inferno.flagrate:
#      description: Allows you to ignite yourself
#      default: true
#    inferno.burningdeaths:
#      description: Allows you to see how many times you have burned to death
#      default: true
#    inferno.burningdeaths.others:
#      description: Allows you to see how many times others have burned to death
#      default: op
#      children:
#        inferno.burningdeaths: true
